version: "3.9"

services:
  tmo:
    image: tmo
    container_name: tmo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GUNICORN_WORKER_NUM=4
