[project]
name = "tmo"
version = "0.1.0"
description = "demo for gov.cloud"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.5",
    "django-bootstrap>=0.2.4",
    "django-crispy-forms>=2.3",
    "django-environ>=0.12.0",
    "pillow>=11.1.0",
]
