name: TMO CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Setup python
      run: uv python install
      with:
        python-version-file: ".python-version"

    - name: Install the project
      run: uv sync --all-extras --dev
      
    - name: Run Tests
      run: uv run  manage.py test

  
